#!/bin/sh

set -e

SCRIPT_PATH="$(dirname -- "$(readlink -f -- "$0")")"

echo "## bootstrap ###################################################################"
"${SCRIPT_PATH}/bootstrap"

cd "${SCRIPT_PATH}/.."

if [ -z "$VENV_NAME" ]; then
    VENV_NAME="env"
fi

. "$VENV_NAME/bin/activate"

echo "## environment & versions ######################################################"
python --version
pip --version
echo "## modules: "
pip freeze
echo "## clean up ####################################################################"
find requests_futures tests -name "*.pyc" -exec rm {} \;
rm -f *.pyc
echo "## begin #######################################################################"
# For now it's just lint...
echo "## lint ########################################################################"
"${SCRIPT_PATH}/lint"
echo "## formatting ##################################################################"
"${SCRIPT_PATH}/format" --check || (echo "Formatting check failed, run ./script/format" && exit 1)
echo "## tests/coverage ##############################################################"
"${SCRIPT_PATH}/coverage"
echo "## complete ####################################################################"
